services:
  api-verixa-blue:
    image: ${SERVICE_WEBHOOK_IMAGE:?set SERVICE_WEBHOOK_IMAGE}:${SERVICE_WEBHOOK_VERSION:?set SERVICE_WEBHOOK_VERSION}

  api-verixa-green:
    image: ${SERVICE_WEBHOOK_IMAGE:?set SERVICE_WEBHOOK_IMAGE}:${SERVICE_WEBHOOK_VERSION:?set SERVICE_WEBHOOK_VERSION}

  api-lgpay-blue:
    image: ${SERVICE_WEBHOOK_IMAGE:?set SERVICE_WEBHOOK_IMAGE}:${SERVICE_WEBHOOK_VERSION:?set SERVICE_WEBHOOK_VERSION}

  api-lgpay-green:
    image: ${SERVICE_WEBHOOK_IMAGE:?set SERVICE_WEBHOOK_IMAGE}:${SERVICE_WEBHOOK_VERSION:?set SERVICE_WEBHOOK_VERSION}

  api-sandbox-blue:
    image: ${SERVICE_WEBHOOK_IMAGE:?set SERVICE_WEBHOOK_IMAGE}:${SERVICE_WEBHOOK_VERSION:?set SERVICE_WEBHOOK_VERSION}

  api-sandbox-green:
    image: ${SERVICE_WEBHOOK_IMAGE:?set SERVICE_WEBHOOK_IMAGE}:${SERVICE_WEBHOOK_VERSION:?set SERVICE_WEBHOOK_VERSION}
