api:
  dashboard: true
  insecure: true

entryPoints:
  verixa:
    address: ":8900"
  lgpay:
    address: ":8902"
  sandbox:
    address: ":8904"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO

accessLog: {}
